### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by ChristianLan1** [davidhamann/python-fmrest#11]
Hi 
I tried to install using pip3 install https://github.com/davidhamann/python-fmrest/archive/master.zip, but got the error below. Any suggestions? Thanks

Collecting https://github.com/davidhamann/python-fmrest/archive/master.zip
  Downloading https://github.com/davidhamann/python-fmrest/archive/master.zip
     - 1.2MB 1.3MB/s
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\CHRIST~1\AppData\Local\Temp\pip-req-build-t_wnnsln\setup.py", line 4, in <module>
        long_description = ld.read()
      File "c:\users\christian lan\appdata\local\programs\python\python36\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 721: character maps to <undefined>
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\CHRIST~1\AppData\Local\Temp\pip-req-build-t_wnnsln\

**Comment by davidhamann** [comment]
This is likely an issue coming from the "preferred encoding" set on your machine.

I just pushed an update. Could you try again with the latest master?

If it works fine, I'll push it to PyPi as well.

**Comment by ChristianLan1** [comment]
> This is likely an issue coming from the "preferred encoding" set on your machine.
> 
> I just pushed an update. Could you try again with the latest master?
> 
> If it works fine, I'll push it to PyPi as well.

Thank you so much for your quick help! It's all good now!

**Comment by davidhamann** [comment]
Great! Version 1.1.1. with the fix is now also on PyPi, so you can now also use `pip install python-fmrest`.
