### ISSUE TITLE
module 'fmrest' has no attribute 'Server'

### ISSUE THREAD

**Issue by Ch0nDa** [davidhamann/python-fmrest#13]
I am having no issues when running on mac.

However, when I run on Ubuntu, I get: 
AttributeError: module 'fmrest' has no attribute 'Server'

I've tested on two different fresh installs of Ubuntu on Raspberry Pi to no avail.

**Comment by davidhamann** [comment]
How did you install it? Via PyPI (`pip install python-fmrest`)?

Can you do a `dir(fmrest)` and `fmrest.__version__` and post the output here? And also what Python version you are using?

**Comment by Ch0nDa** [comment]
Installed via pip (pip install python-fmrest, pip3 install python-fmrest)

Here is my output.  I am not sure if I am doing dir(fmrest) and fmrest.__version__ correctly.  Is this done within Python?

Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fmrest
>>> dir(fmrest)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>> fmrest.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'fmrest' has no attribute '__version__'
>>> fmrest._version_
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'fmrest' has no attribute '_version_'
>>>

**Comment by Ch0nDa** [comment]
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> dir(fmrest)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'fmrest' is not defined
>>> fmrest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'fmrest' is not defined
>>> import fmrest
>>> dir(fmrest)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>> fmrest.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'fmrest' has no attribute '__version__'
>>> fmrest._version_
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'fmrest' has no attribute '_version_'
>>>

**Comment by Ch0nDa** [comment]
the double underscores are not showing up in my github comment fyi.

**Comment by Ch0nDa** [comment]
This command fixed it: pip install python-fmrest  

For Ubuntu: pip3 install python-fmrest

I was using the wrong command: pip install fmrest

As stated on Filemaker Community, thanks so much. :)  I'll be around.
