### ISSUE TITLE
FileMaker 19 compatible?

### ISSUE THREAD

**Issue by Daniel-01** [davidhamann/python-fmrest#21]
Is fmrest compatible with File Maker Server 19?
When I call login() I get:
"fmrest.exceptions.BadJSON: Expecting value: line 1 column 1 (char 0), 200 http response, content-type: text/html;charset=utf-8" 
I am using fmrest 1.0.2.

**Comment by davidhamann** [comment]
There are no known issues with FMS 19; all tests pass.

Judging from your error message, it seems FMS isn't returning JSON data but an HTML page. Can you double check that the Data API is enabled on the server?

If it is and still doesn't work, can you upgrade to v1.3.0 – the latest – of python-fmrest? The v1.0.2 is around 2 years old.

**Comment by Daniel-01** [comment]
Good to know that it is compatible.
It is probably some setup issue then.
1.0.2 is the version I got with "pip install python-fmrest".

**Comment by davidhamann** [comment]
You might have downloaded it before versions were pinned or have the version pinned yourself? Or running Python3 < 3.6?

Try `pip install python-fmrest --upgrade` to see if it gives you a newer version, or `pip install python-fmrest==1.3.0` for a specific version, respectively.

You can see older releases over at [PyPI](https://pypi.org/project/python-fmrest/#history) or here at [GitHub](https://github.com/davidhamann/python-fmrest/releases) with some comments.

**Comment by Daniel-01** [comment]
I am running Python 3.5 which may explain why I get fmrest 1.0.2.
Anyway, I can access the database now. It was a setup issue.
