### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by subbe98** [davidhamann/python-fmrest#28]
Hi, how do I change the timeout constant in const.py, to something higher? Like 20 or 30. Im trying to generate PDFs with a perform_script, but some PDFs times out due to read_timeout = 10. I installed the wrapper via pip, but not sure how to use my own modified version of the wrapper.

**Comment by davidhamann** [comment]
You can set an environment variable called `fmrest_timeout` with the number of seconds you'd like the timeout to be.
