### ISSUE TITLE
[Question] Edit records within a portal

### ISSUE THREAD

**Issue by Minkiu** [davidhamann/python-fmrest#31]
Hey there!

Thanks for this lovely package, I am doing testing to try update a FileMaker table with it, the steps I am following are:
1) Get desired `record`.
2) Loop through all the records **within a portal** in the `record` ( `for rec in record[0]['portal_Other_Table']` )
3) Do stuff to `rec` and update it. (I am following this example to do so: https://github.com/davidhamann/python-fmrest/blob/master/examples/editing_data.ipynb)

But I am facing a `fmrest.exceptions.FileMakerError: FileMaker Server returned error 101, Record is missing`, I tried adding the `data_sources=[{'database': 'Other_Table'}]` to the FileMaker session (with and without username/password, as per https://github.com/davidhamann/python-fmrest/blob/master/examples/multiple_data_sources.ipynb) and it doesn't work.

I am new to FileMaker, so sorry if I am missing something obvious, so the question is:
Are we able to change records within portals with `python-fmrest`?

**Comment by Minkiu** [comment]
I guess the answer is no, but just for the record, I ended up doing two sessions (for different layouts), and using the IDs fetched the relating data (the one that the portal was showing) and updated accordingly.

I leave open in case you want to add anything but I believe this can be closed.

**Comment by davidhamann** [comment]
Unfortunately, you currently cannot edit portal data directly through the record instance. But you _can_ edit the portal records through `edit_record` by just creating a dict of what to edit.

Example:

```
fms.edit_record(<your record ID>, field_data={'some_field': 'test'}, portals={'notes': [{'Notes::note': 'hello', 'recordId': <your portal record ID>}]})
```

`notes` would be the portal's object name, `Notes::note` the fully-qualified field name, and `recordId` the ID of the portal record to edit.

Also see the comments here: https://github.com/davidhamann/python-fmrest/blob/master/fmrest/server.py#L224

Hope this helps!

PS.: I don't think you need two sessions (even if not doing the edits through the portal). You could switch the layout in the same session and thus skip the overhead of creating another session (opening file, logging in, etc.).
