### ISSUE TITLE
Help with class Server login

### ISSUE THREAD

**Issue by kyletov** [davidhamann/python-fmrest#36]
Hello, I'm getting this error when trying to login using the `Server` class:
```
fmrest.exceptions.FileMakerError: FileMaker Server returned error 212, Authorization header 'Basic' invalid.
```
Any help or guidance on this would be great!

**Comment by davidhamann** [comment]
Does the error appear when attempting to login or after the initial login? Can you provide a code snippet and the full trace?

**Comment by kyletov** [comment]
Hey, I'm trying again and seems like I'm not running into that issue anymore, I got the impression that I needed to include data_sources when initializing fmrest.Server like `data_sources=[{'database': 'Contacts', 'username': 'admin', 'password': 'admin'}]` (from code docs).

When I removed it, I was able to login using the format below (same as the example from the docs):
```
>>> fms = fmrest.Server('https://your-server.com',
                        user='admin',
                        password='admin',
                        database='Contacts',
                        layout='Contacts')
>>> fms.login()
>>> record = fms.get_record(1)
>>> record.name
John Doe
```

**Comment by davidhamann** [comment]
Glad it works now. The `data_sources` is in fact only needed if you want to authenticate to additional DBs.
