### ISSUE TITLE
How to display results of find dynamically into a template?

### ISSUE THREAD

**Issue by chicodelacruz** [davidhamann/python-fmrest#39]
How to display results of find dynamically into a template?

**Comment by davidhamann** [comment]
Can you elaborate where you are stuck / what you are trying to do with a small sample code? Usually, once you have a `Foundset` you can just iterate over it and then extract the fields from the records in the set.

**Comment by chicodelacruz** [comment]
Hi, having trouble here. I'm using Django Framework.

I can successfully display on my terminal the response of the API. I'm just having a problem with how to display it dynamically on my template.

My plan is upon finding a field, it will show the result without having reloading the page. If there is a chance that you have some tips on this.

Here is my code.

![Screenshot at Jan 17 10-33-50](https://user-images.githubusercontent.com/28640114/149702830-99641dba-d81d-4b4c-a415-22a210455c83.png)

![Screenshot at Jan 17 10-34-21](https://user-images.githubusercontent.com/28640114/149702836-e3ed5d3f-c8cd-4625-9efd-cf9ce935bdda.png)

![Screenshot at Jan 17 10-34-58](https://user-images.githubusercontent.com/28640114/149702844-dd4b938b-3096-4778-af54-1eb903045b30.png)

![Screenshot at Jan 17 10-35-35](https://user-images.githubusercontent.com/28640114/149702856-cbf6d9ab-9f20-4734-a977-729f82a9d412.png)

**Comment by davidhamann** [comment]
Sorry, cannot help with Django as I'm not using it.

Just a few ideas: you're using `record.values` in the template vs `record.values()` in the print. Other than that I would try to not pass the whole list to the template but maybe try to give the template only a specific field (like `record.RefNo`) or "stringify" the list first (like `json.dumps()`) and see if that makes a difference.

**Comment by davidhamann** [comment]
PS.: I removed your first screenshot as it contained a "real-looking" user, password and server address – just in case.

In case it was real, I would recommend to change it asap :-)

**Comment by chicodelacruz** [comment]
I got NameError: name 'NoMatch' is not defined or NameError: name 'FileMakerError' is not defined
