### ISSUE TITLE
additional info on data types and their formats when creating records

### ISSUE THREAD

**Issue by DonPasquale** [davidhamann/python-fmrest#42]
As I did not find anything in the examples and not even on Claris' website, it took me a while to figure out the correct (?) way to write date, time and timestamps to new records. 

So maybe worth an additional (to be created) 'create_data.ipynb' in the examples directory?

Possibly along the lines of:

rec_created = fms.create_record({'mytext': 'Mars', 
								 'mynum': 667, 
								 'mydate': '2/22/2022', # month/day/year
								 'mytime': '9:15:55 PM',  # alternative 24h format
								 'mystamp': '2/22/2022 9:15:55 PM', 
								})
print(rec_created)

rec_created2 = fms.create_record( {} ) # empty dict
print(rec_created2)

new_data = {
			'mytext': 'Venus', 
			'mynum': 1234567, 
			'mydate': '02/22/2022', # month/day/year, with leading zero
			'mytime': '21:15:55',  # alternative format, no 'AM/PM', see above
			'mystamp': '2/22/2022 21:15:55', 
			}
rec_created3 = fms.create_record(new_data)
print(rec_created3)

**Comment by DonPasquale** [comment]
If one wants to retrieve the supported date and time formats, access the API metadata:

`https://[your_host]/fmi/data/vLatest/productInfo`

Which may return something similar to this, including `dateFormat`, `timeFormat` and `timeStampFormat`:

`{"response":
    {"productInfo":
        {"name":"FileMaker Data API Engine",
         "buildDate":"03/16/2020",
         "version":"18.0.4.428",
         "dateFormat":"MM/dd/yyyy",
         "timeFormat":"HH:mm:ss",
         "timeStampFormat":"MM/dd/yyyy HH:mm:ss"}},
         "messages":[
            {"code":"0",
             "message":"OK"}
         ]
}`

**Comment by davidhamann** [comment]
Thanks for the info and suggestion. The date/stamp format in FM is definitely odd and, looking at how times are stored internally, one could assume to be able just send an integer to get around the odd format, like `63780484673` for `2022-02-15 01:17:53`. However, this only works with the FM client, oh well...

If you like you can create an example file with the sample data and mention the product endpoint as well. Happy to merge it.

**Comment by DonPasquale** [comment]
> If you like you can create an example file with the sample data and mention the product endpoint as well. Happy to merge it.

I would be willing to try and contribute, but I am unfortuantely not familiar with the ".ipynb" files. Could I post a basic Python script instead?

Also, the only FMS I have access to is in a private network, not sure what you mean by "product endpoint".

Many thanks.

**Comment by DonPasquale** [comment]
I opened a pull request #43 , not sure this is what you expected...

**Comment by DonPasquale** [comment]
Many thanks!
