### ISSUE TITLE
Digital Signature

### ISSUE THREAD

**Issue by chicodelacruz** [davidhamann/python-fmrest#45]
Good Day,

Is it possible to implement a digital signature and upload it as a container?

**Comment by davidhamann** [comment]
You mean "digital signature" in terms of cryptography or do you mean an image of an actual signature to store in a media container?

Can you describe your use-case a bit more? Thanks.

**Comment by chicodelacruz** [comment]
Hi David,

I have collected a digital signature as an image and what to pass it to the filemaker container field. Is that possible?

**Comment by davidhamann** [comment]
Yes, you could use the `upload_container` method. Here's an example: https://github.com/davidhamann/python-fmrest/blob/master/examples/uploading_container_data.ipynb
