### ISSUE TITLE
Retrieve a list of all available databases hosted on FMS

### ISSUE THREAD

**Issue by DonPasquale** [davidhamann/python-fmrest#47]
It would be very nice to have the possibilty to query FMS for a list of all available databases, depending on _being logged in or not_ and depending on the FMS preference for _filtering databases_ set to 'on' or 'off'. See #46

**Comment by davidhamann** [comment]
Thanks for the PR. I'll take a look in the next couple of days.

**Comment by davidhamann** [comment]
See #46
