### ISSUE TITLE
New tag/release?

### ISSUE THREAD

**Issue by DonPasquale** [davidhamann/python-fmrest#52]
Would the new version (1.5.1) maybe justify a new tag / release?

**Comment by davidhamann** [comment]
Yes, sure. Thanks for the nudge! I'll prepare it in the coming week.

**Comment by davidhamann** [comment]
* https://github.com/davidhamann/python-fmrest/releases/tag/v1.5.1
* https://pypi.org/project/python-fmrest/1.5.1/

🚀
