### ISSUE TITLE
botocore notauthorizedexception when deploying CloudServer on Heroku

### ISSUE THREAD

**Issue by TDKorn** [davidhamann/python-fmrest#54]
Hi, 

I think this is more of an issue with Cognito/Claris than this package, but wondering if you’ve got any suggestions for the issue where generating a token locally works fine, but when hosted leads to 

`botocore.errorfactory.notauthorizedexception: an error occurred (notauthorizedexception) when calling the respondtoauthchallenge operation: unable to login because of security reasons.`

There’s a post about it on the community forums but doesn’t seem like there’s an actual solution
 
https://community.claris.com/en/s/question/0D53w00005SS3ijCAD/filemaker-cloud-api-unable-to-login-because-of-security-reasons-when-running-it-from-any-of-the-aws-servers

thanks!

**Comment by davidhamann** [comment]
See #55 for more info (was merged). If anyone has more info/alternative workarounds, feel free to re-open/comment here.
