### ISSUE TITLE
FileMaker server version > 17 in README

### ISSUE THREAD

**Issue by da-** [davidhamann/python-fmrest#57]
The README says it requires filemaker server 17. I see from closed issues that it should work with version 19. If that's correct, would you be open to changing:

> You need Python 3.6 and FileMaker Server/Cloud 17.

to 
> You need Python 3.6 **or newer**, and FileMaker Server/Cloud 17 **or newer**.

**Comment by davidhamann** [comment]
Good point. Have changed it. Thanks!
