### ISSUE TITLE
How to specify layout name?

### ISSUE THREAD

**Issue by nexgen** [davidhamann/python-fmrest#58]
It seems I can specify layout name while login only. How can I change it later to query different data from different layouts?

**Comment by davidhamann** [comment]
You can either set the `Server` instance's `layout` attribute again or set the `request_layout` in the method calls directly.

So either `fms.layout = 'my_custom_layout` or, for example,`fms.get_records(request_layout='my_custom_layout')` (given `fms` is the `Server` instance). The latter would keep your default layout as defined during login.

**Comment by nexgen** [comment]
Thank you.
