### ISSUE TITLE
Server instance destructor error after connection error

### ISSUE THREAD

**Issue by PeterWagemans** [davidhamann/python-fmrest#65]
Hi David,
Ian and I are including fmrest into the WB2 python project, and it's great to have it.
We are running into a bit of a problem when e.g. the admin forgot to enable the Data API on the server.
In that case fmrest returns an exception with server error 502, which we can trap.
But the destructor of the Server instance has a problem I think. It tries to log out. While it was never able to log in.
This generates another error that I don't know how to trap.

I'm just a noob in Python, but maybe it's a good idea to check in the destructor if the connection was successful.
Thanks, and keep up your great work!

**Comment by davidhamann** [comment]
Hi Peter,

I assume you're using the context manager (`with`)? Would you mind pasting your code snippet and the traceback here?

**Comment by PeterWagemans** [comment]
Morning David,

Here’s a simple function we use to get the id of 1 record in a globals table

I disable the DAPI connector and run it:
> def get_payload_global_id():
>     logging.debug("Getting payload_global_id")
>     fms = get_fmserver_connection("post")
>     with fms as my_server:
>         try:
>             my_server.login()
>             records = my_server.get_records(limit=1)
>             record = records[0]
>             record_id = record.record_id
>             return record_id
>         except fmrest.exceptions.FileMakerError as e:
>             logging.exception(e)
>             print("ok, so that didn't go according to plan")
>             print(e)
>             return None

Here’s the traceback:

> Traceback (most recent call last):
>   File "wb.py", line 49, in <module>
>     global_record_id = get_payload_global_id()
>   File "wb_server.py", line 53, in get_payload_global_id
>     return None
>   File "venv/lib/python3.9/site-packages/fmrest/server.py", line 135, in __exit__
>     self.logout()
>   File "venv/lib/python3.9/site-packages/fmrest/server.py", line 208, in logout
>     self._call_filemaker('DELETE', path)
>   File "venv/lib/python3.9/site-packages/fmrest/server.py", line 927, in _call_filemaker
>     raise BadJSON(ex, response) from None
> fmrest.exceptions.BadJSON: Expecting value: line 1 column 1 (char 0), 502 http response, content-type: text/html; charset=utf-8
> 
> Process finished with exit code 1


There is some intermittent problem though where pycharm keeps being unhappy about the fmrest import and requirements and this problem when we use

> except fmrest.exceptions.FileMakerError as e:
> Cannot find reference 'exceptions' in '__init__.py'

Maybe it has nothing to do with this issue, maybe I’m just not seeing it, which is much more probable :-)

Cheers! — peter

———————
🔆Clarify - FileMaker development, training & support –– ***@***.***

**Comment by davidhamann** [comment]
Thanks for the additional data.

As a workaround you could do the login outside the context manager and then catch the root fmrest exception:

```
try:
    fms.login()
except fmrest.exceptions.FMRestException as exc:
    print(f"Unable to login via DAPI due to: {exc}")
    return

with fms:
    # ... do your thing as normal; during exit of context manager logout() will be called
```

But you're right that `logout` should be a no-op if there's no token in the first place. I'll see if I can make that change in a future version.

**Comment by davidhamann** [comment]
From version `1.7.2` you can now catch the `BadGatewayError` directly:

```
try:
    fms.login()
    # ...
except fmrest.exceptions.BadGatewayError as exc:
    print(f"Something went wrong: {exc}")

>> Something went wrong: Web server responded with a Bad Gateway error. Check if the Data API is enabled and responding.
```

Additionally, the logout in the `__exit__` will now only be executed when a token exists.

**Comment by PeterWagemans** [comment]
Thanks David! — peter

———————
🔆Clarify - FileMaker development, training & support –– ***@***.***
