### ISSUE TITLE
read time-out

### ISSUE THREAD

**Issue by wimdecorte** [davidhamann/python-fmrest#78]
Getting this error when running a script that takes some time:

`fmrest.exceptions.RequestException: Request error: HTTPSConnectionPool(host='server.ets.fm', port=443): Read timed out. (read timeout=10)`

Normally I'd parcel off the long-running task through PSoS-no-wait in the DAPI script but bugs in FMS prevent me from doing that.

How can I change the timeout?

Thanks,
Wim

**Comment by wimdecorte** [comment]
disregard, I found the setting in the server init.

**Comment by nexgen** [comment]
I'm experiencing same problem for the script taking long time. Where to set the timeout?

**Comment by nexgen** [comment]
Also, is there a way to run perform script without waiting for the result?

**Comment by wimdecorte** [comment]
That's just native FM functionality, not part of a wrapper like this.
To do this: have the script that you call through the Data API use "perform script on server" to call the actual script you want executed and use the "no wait" option.
That means that the Data API session will end quickly but the called script will run asynchronously.

Two things to keep in mind:
1) there are bugs in older versions of FMS where this will fail, so for reliability you have to be on the latest FMS
2) this construct then uses the FMSE scripting engine in FMS, not the Data API script engine so the script step compatibility is different.  Typically not a big problem since FMSE usually has support for more script steps than the other two script engines.

**Comment by nexgen** [comment]
Nice to see you here @wimdecorte Thank you for the solution.

I was trying this recursive call:
```
If [ Position ( Get(ApplicationVersion) ; "Data API" ; 1 ; 1 ) > 1 ]
    # forward call to Server Scripting Engine
    Perform Script on Server [ Specified: By name ; Get(ScriptName) ; Parameter: Get(ScriptParameter) ; Wait for completion: On ]
    Exit Script [ Text Result: Get(ScriptResult) ]
End If

Exit Script [ Text Result: "MBS: " & MBS("Version") & ", Server: " & Get(ApplicationVersion) ]```

It didn't work if I call a script from external data source.

However, if I create a separate script and call psos from there, then it is working.
