### ISSUE TITLE
Is that possible to get records by multiple ids?

### ISSUE THREAD

**Issue by albarrasera** [davidhamann/python-fmrest#79]

**Comment by davidhamann** [comment]
If you have a field containing the ID you could do a `find` and pass multiple requests in the query array. For example:

```
[{'my_id': '==1234'}, {'my_id': '==5678'}]
```

**Comment by albarranaufala** [comment]
> If you have a field containing the ID you could do a `find` and pass multiple requests in the query array. For example:
> 
> ```
> [{'my_id': '==1234'}, {'my_id': '==5678'}]
> ```

Thank you for your answer! Then if there is no field containing ID, is that possible to get records by multiple recordIds?

**Comment by davidhamann** [comment]
Not directly. You could create a field in FM that calculates the record ID and then do a find request on that field. Or call an FM script which takes a bunch of IDs and returns the results you want. Or possibly set IDs in a global field and then get data via a portal/relationship. It really depends on your use-case but would always require a modification to your FM app.

Unfortunately, the Data API itself has no direct endpoint to get a foundset for a given set of (internal) records IDs.

If you have very few records you might also be able to just do `get_records` to get all records in the table and then filter in your program.

Does the table you are querying not have a primary key or other unique identifier you could use? I guess doing a find with multiple queries would be the best approach.

Where does your list of record IDs come from in the first place?

**Comment by albarrasera** [comment]
> Not directly. You could create a field in FM that calculates the record ID and then do a find request on that field. Or call an FM script which takes a bunch of IDs and returns the results you want. Or possibly set IDs in a global field and then get data via a portal/relationship. It really depends on your use-case but would always require a modification to your FM app.
> 
> Unfortunately, the Data API itself has no direct endpoint to get a foundset for a given set of (internal) records IDs.
> 
> If you have very few records you might also be able to just do `get_records` to get all records in the table and then filter in your program.
> 
> Does the table you are querying not have a primary key or other unique identifier you could use? I guess doing a find with multiple queries would be the best approach.
> 
> Where does your list of record IDs come from in the first place?

I see. Thanks for the explanation. I will close this issue.
