### ISSUE TITLE
Example for accessing FMP database doesn't work...

### ISSUE THREAD

**Issue by ursomniac** [davidhamann/python-fmrest#8]
>>> import fmrest
>>> fms = fmrest.Server( credentials, etc. )
Attribute Error:  module 'fmrest' has no attribute 'Server'
>>> dir(fmrest)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']

Please advise?

**Comment by davidhamann** [comment]
Could you give me a bit more information on how you installed `python-fmrest`?

Also, can you give me your Python version and the line of `python-fmrest` showing when you do `pip list`?

**Comment by davidhamann** [comment]
Closed due to inactivity. Please reply with more information if you still need help.
